# Generated by Django 3.1.5 on 2022-03-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(null=True)),
                ('date', models.DateTimeField(null=True)),
                ('photo', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
