# Generated by Django 3.1.5 on 2021-02-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20210207_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='hit',
            unique_together={('ip', 'post', 'date')},
        ),
    ]
