# Generated by Django 3.1.5 on 2021-12-07 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_commentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_comment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.comment'),
        ),
    ]
